#!/usr/bin/env python3
"""
build_compression_payloads.py — deterministically generate the representative
payloads fixture used to measure proxy-pipeline token reduction (TASK-012).

Output: .specify/evals/011-context-compression-governance/golden-session/payloads.json

Payloads mirror compressible harness traffic — multi-turn sessions with large
tool-role JSON dumps (repo scans / file listings). Fully deterministic (no
randomness, no timestamps) so the committed fixture and the benchmark are
reproducible. Run this to (re)generate the fixture; commit the result.

Governs: specs/011-context-compression-governance (TASK-012).
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

MODEL = "claude-sonnet-4-5-20250929"
MODEL_LIMIT = 200000


def _tool_dump(n_rows: int) -> str:
    rows = [
        {
            "id": i,
            "path": f"src/module_{i}.py",
            "bytes": i * 37,
            "status": "unchanged",
            "owner": f"team-{i % 5}",
            "notes": "no change detected in this module since the last governed scan",
        }
        for i in range(n_rows)
    ]
    return json.dumps({"rows": rows})


def build_payloads(n_sessions: int = 3, turns: int = 12, rows: int = 200) -> list:
    payloads = []
    for s in range(n_sessions):
        messages = []
        for t in range(turns):
            messages.append({"role": "user", "content": f"session {s} step {t}: scan repo"})
            messages.append({"role": "tool", "content": _tool_dump(rows)})
        payloads.append(messages)
    return payloads


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate the compression payloads fixture.")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--sessions", type=int, default=3)
    parser.add_argument("--turns", type=int, default=12)
    parser.add_argument("--rows", type=int, default=200)
    args = parser.parse_args(argv)

    out = (
        pathlib.Path(args.repo)
        / ".specify" / "evals" / "011-context-compression-governance"
        / "golden-session" / "payloads.json"
    )
    doc = {
        "description": "Representative outbound payloads for measuring proxy-pipeline "
        "token reduction via headroom TransformPipeline.simulate() (TASK-012). "
        "Deterministically generated by build_compression_payloads.py; commit the result.",
        "model": MODEL,
        "model_limit": MODEL_LIMIT,
        "generated_by": "scripts/build_compression_payloads.py",
        "params": {"sessions": args.sessions, "turns": args.turns, "rows": args.rows},
        "payloads": build_payloads(args.sessions, args.turns, args.rows),
    }
    out.write_text(json.dumps(doc, indent=2))
    print(f"wrote {out} ({args.sessions} sessions x {args.turns} turns x {args.rows} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
